# Book settings
title: ASTROBIOLOGY 200
author: Evert Duran
logo: astro_logo.png

latex:
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  url                       : https://github.com/edur409/ASTROBIOLOGY200  # Online location of your book
  #book_path                 : path/to/book  # Optional path to your book, relative to the repository root
  branch                    : master  # Which branch of the repository should be used when creating links (optional)

launch_buttons:
  binderhub_url: "https://mybinder.org"  # The URL for your BinderHub (e.g., https://mybinder.org)
  thebelab                  : true
